description = "\u001b[1;36mosc94\u001b[22;39m: Library for handling progress bar sequences (OSC 9;4)."

[[recipes]]
names = ["build", "b"]
description = "\u001b[4mB\u001b[24muild release binary"
arguments = []
command = ["cargo", "build", "--release", "--features=cli"]

[[recipes]]
names = ["run", "r"]
description = "Compile and \u001b[4mr\u001b[24mun"
arguments = ["*rest"]
command = ["cargo", "run", "--features=cli", "--", ["*rest"]]

[[recipes]]
names = ["example", "e"]
description = "Compile and run given \u001b[4me\u001b[24mxample"
arguments = ["example", "*rest"]
command = ["cargo", "run", "--example", ["example"], "--", ["*rest"]]

[[recipes]]
names = ["test", "t"]
description = "Run \u001b[4mt\u001b[24mests"
arguments = ["*rest"]
command = ["cargo", "test", ["*rest"]]

[[recipes]]
names = ["version", "v"]
description = "Set or get \u001b[4mv\u001b[24mersion"
arguments = ["?version"]
command = ["./scripts/version.sh", ["?version"]]
